include $(GOROOT)/src/Make.inc

TARG=percolation
GOFILES=\
	energetics.go\
	environment.go\
	grid.go\
	json.go\
	monte_carlo.go\
	point.go\
	point_set.go\
	random.go\
	utility.go
CGOFILES=\
	matrix.go

include $(GOROOT)/src/Make.pkg
