include $(GOROOT)/src/Make.inc

TARG=percolation
GOFILES=\
	analyze_clusters.go\
	energetics.go\
	environment.go\
	grid.go\
	json.go\
	monte_carlo.go\
	point.go\
	point_set.go\
	random.go\
	vector_sort.go
CGOFILES=\
	matrix.go\
	solve1d.go

include $(GOROOT)/src/Make.pkg
